import { expect, test } from '@playwright/test'

test('story to reviewed media and rendered timeline', async ({ page }) => {
  const suffix = Date.now().toString(36)
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: '没有账户？立即注册' }).click()
  await page.getByLabel('显示名称').fill('E2E Producer')
  await page.getByLabel('电子邮箱').fill(`e2e-${suffix}@example.com`)
  await page.getByLabel('密码').fill('StrongPassword123')
  await page.getByRole('button', { name: '创建账户' }).click()
  await expect(page.getByRole('heading', { name: '你的工作台' })).toBeVisible()
  await page.getByRole('button', { name: '新建工作空间' }).click()
  await page.getByLabel('工作空间名称').fill('E2E Studio')
  await page.getByRole('button', { name: '创建', exact: true }).click()
  await page.getByRole('button', { name: '新建项目' }).click()
  await page.getByLabel('项目名称').fill('Dawn Courier')
  await page.getByRole('button', { name: '创建', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Dawn Courier' })).toBeVisible()

  await page.locator('.sidebar').getByRole('link', { name: '故事工作室' }).click()
  await page.getByPlaceholder('故事标题').fill('The Dawn Courier')
  await page.getByPlaceholder('粘贴真实故事或小说片段…').fill('At dawn a courier climbs the city rooftop. Rain glows around her. She looks toward the sun and says the city is waking up.')
  await page.getByRole('button', { name: '导入原作' }).click()
  await expect(page.getByText('故事已导入。')).toBeVisible()
  await page.getByRole('button', { name: '建立索引' }).click()
  await expect(page.getByText('故事已进入项目知识索引。')).toBeVisible()

  await page.locator('.sidebar').getByRole('link', { name: '角色工作室' }).click()
  await page.getByPlaceholder('角色姓名').fill('Courier')
  await page.getByPlaceholder('五官与辨识特征').fill('Determined eyes')
  await page.getByPlaceholder('颜色、长度、造型').fill('Short dark hair')
  await page.getByPlaceholder('常用服装').fill('Blue raincoat')
  await page.getByRole('button', { name: '创建角色' }).click()
  await expect(page.getByText('角色草稿已创建。')).toBeVisible()
  await page.getByRole('button', { name: '激活' }).click()
  await expect(page.getByText('版本已设为正式。')).toBeVisible()

  await page.locator('.sidebar').getByRole('link', { name: '剧集与场景' }).click()
  await page.getByPlaceholder('第一集 · 标题').fill('First Light')
  await page.getByRole('button', { name: '创建剧集' }).click()
  await page.getByPlaceholder('例如：EXT. CITY ROOFTOP - NIGHT').fill('EXT. CITY ROOFTOP - DAWN')
  await page.getByRole('button', { name: '添加场景' }).click()
  await expect(page.getByText('场景已创建。')).toBeVisible()

  await page.locator('.sidebar').getByRole('link', { name: '分镜工作室' }).click()
  await page.getByRole('button', { name: '创建镜头' }).click()
  await page.getByLabel('出镜角色').selectOption({ label: 'Courier' })
  await page.getByLabel('画面描述').fill('A lone courier stands on a rainy rooftop at dawn')
  await page.getByLabel('对白').fill('城市醒来了。')
  await page.getByLabel('时长（秒）').fill('2')
  await page.getByRole('button', { name: '保存镜头' }).click()
  await expect(page.getByText('镜头已创建。')).toBeVisible()
  await page.getByRole('button', { name: '规划完成' }).click()
  await page.getByRole('button', { name: '分镜就绪' }).click()
  await page.getByRole('button', { name: '生成图像' }).click()
  await expect(page.getByRole('button', { name: '生成视频' })).toBeVisible({ timeout: 60_000 })
  await page.getByRole('button', { name: '生成视频' }).click()
  await expect(page.getByRole('button', { name: '生成配音' })).toBeVisible({ timeout: 60_000 })
  await page.getByRole('button', { name: '生成配音' }).click()

  await page.locator('.sidebar').getByRole('link', { name: '审核' }).click()
  await expect(page.getByText('待处理镜头')).toBeVisible()
  await page.getByRole('button', { name: /Shot 01/ }).click()
  await expect(page.getByText('Inspector')).toBeVisible()
  await expect(page.locator('aside video')).toBeVisible()
  await expect(page.locator('aside audio')).toBeVisible()
  await page.getByRole('button', { name: '通过' }).click()
  await page.locator('.sidebar').getByRole('link', { name: '时间线' }).click()
  await page.getByRole('button', { name: '创建时间线' }).click()
  await page.getByRole('button', { name: '同步已审镜头' }).click()
  await page.getByRole('button', { name: '渲染成片' }).click()
  await expect(page.getByRole('heading', { name: '最终成片' })).toBeVisible({ timeout: 60_000 })
  await page.locator('video').evaluate(async (video: HTMLVideoElement) => {
    if (video.readyState < 2) await new Promise<void>(resolve => video.addEventListener('loadeddata', () => resolve(), { once: true }))
    video.currentTime = Math.min(0.8, video.duration / 2)
    await new Promise<void>(resolve => video.addEventListener('seeked', () => resolve(), { once: true }))
  })
  await page.screenshot({ path: '../evidence/ui-final.png', fullPage: true })
  expect(errors).toEqual([])
})
