"""initial schema

Revision ID: e79da6243b7a
Revises:
Create Date: 2026-09-23 00:47:06.103234
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e79da6243b7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_node', sa.String(length=80), nullable=False),
    sa.Column('decision_summary', sa.Text(), nullable=False),
    sa.Column('retrieved_sources', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_workspace_id'), 'agent_runs', ['workspace_id'], unique=False)
    op.create_table('assets',
    sa.Column('bucket', sa.String(length=120), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_job_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_workspace_id'), 'assets', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('permission_result', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('safe_summary', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('character_relationships',
    sa.Column('source_character_id', sa.String(length=36), nullable=False),
    sa.Column('target_character_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_relationships_project_id'), 'character_relationships', ['project_id'], unique=False)
    op.create_index(op.f('ix_character_relationships_workspace_id'), 'character_relationships', ['workspace_id'], unique=False)
    op.create_table('characters',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active_version_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_project_id'), 'characters', ['project_id'], unique=False)
    op.create_index(op.f('ix_characters_workspace_id'), 'characters', ['workspace_id'], unique=False)
    op.create_table('episodes',
    sa.Column('episode_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'episode_no')
    )
    op.create_index(op.f('ix_episodes_project_id'), 'episodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_episodes_workspace_id'), 'episodes', ['workspace_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('provider_request_id', sa.String(length=160), nullable=True),
    sa.Column('remote_job_id', sa.String(length=160), nullable=True),
    sa.Column('lease_owner', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('callback_received_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('tool_call_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_generation_jobs_project_id'), 'generation_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_workspace_id'), 'generation_jobs', ['workspace_id'], unique=False)
    op.create_index('ix_generation_status_lease', 'generation_jobs', ['status', 'lease_expires_at'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_project_id'), 'knowledge_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_workspace_id'), 'knowledge_documents', ['workspace_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=160), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_key')
    )
    op.create_index(op.f('ix_outbox_events_project_id'), 'outbox_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_workspace_id'), 'outbox_events', ['workspace_id'], unique=False)
    op.create_table('project_bibles',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_bibles_project_id'), 'project_bibles', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_bibles_workspace_id'), 'project_bibles', ['workspace_id'], unique=False)
    op.create_table('story_sources',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_sources_project_id'), 'story_sources', ['project_id'], unique=False)
    op.create_index(op.f('ix_story_sources_workspace_id'), 'story_sources', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('character_versions',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dna', sa.JSON(), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'version_no')
    )
    op.create_index(op.f('ix_character_versions_character_id'), 'character_versions', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_versions_project_id'), 'character_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_character_versions_workspace_id'), 'character_versions', ['workspace_id'], unique=False)
    op.create_table('generation_outputs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_outputs_project_id'), 'generation_outputs', ['project_id'], unique=False)
    op.create_index(op.f('ix_generation_outputs_workspace_id'), 'generation_outputs', ['workspace_id'], unique=False)
    op.create_table('knowledge_versions',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_versions_project_id'), 'knowledge_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledge_versions_workspace_id'), 'knowledge_versions', ['workspace_id'], unique=False)
    op.create_table('pending_actions',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_project_id'), 'pending_actions', ['project_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_workspace_id'), 'pending_actions', ['workspace_id'], unique=False)
    op.create_table('scenes',
    sa.Column('episode_id', sa.String(length=36), nullable=False),
    sa.Column('scene_no', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'scene_no')
    )
    op.create_index(op.f('ix_scenes_episode_id'), 'scenes', ['episode_id'], unique=False)
    op.create_index(op.f('ix_scenes_project_id'), 'scenes', ['project_id'], unique=False)
    op.create_index(op.f('ix_scenes_workspace_id'), 'scenes', ['workspace_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('used_refresh_hashes', sa.JSON(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('timelines',
    sa.Column('episode_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('final_asset_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timelines_project_id'), 'timelines', ['project_id'], unique=False)
    op.create_index(op.f('ix_timelines_workspace_id'), 'timelines', ['workspace_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('agent_run_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('arguments_hash', sa.String(length=64), nullable=False),
    sa.Column('resource_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('safe_summary', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_project_id'), 'tool_calls', ['project_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_workspace_id'), 'tool_calls', ['workspace_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('token_input', sa.Integer(), nullable=False),
    sa.Column('token_output', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('video_seconds', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_project_id'), 'usage_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_usage_records_workspace_id'), 'usage_records', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('budget_limit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('budget_used', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('budget_reserved', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('shots',
    sa.Column('episode_id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('shot_no', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.String(length=60), nullable=False),
    sa.Column('camera_angle', sa.String(length=60), nullable=False),
    sa.Column('camera_movement', sa.String(length=60), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('dialogue', sa.Text(), nullable=False),
    sa.Column('emotion', sa.String(length=80), nullable=False),
    sa.Column('character_ids', sa.JSON(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('current_image_asset_id', sa.String(length=36), nullable=True),
    sa.Column('current_video_asset_id', sa.String(length=36), nullable=True),
    sa.Column('current_audio_asset_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'shot_no')
    )
    op.create_index(op.f('ix_shots_episode_id'), 'shots', ['episode_id'], unique=False)
    op.create_index(op.f('ix_shots_project_id'), 'shots', ['project_id'], unique=False)
    op.create_index(op.f('ix_shots_scene_id'), 'shots', ['scene_id'], unique=False)
    op.create_index(op.f('ix_shots_workspace_id'), 'shots', ['workspace_id'], unique=False)
    op.create_table('timeline_tracks',
    sa.Column('timeline_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_tracks_project_id'), 'timeline_tracks', ['project_id'], unique=False)
    op.create_index(op.f('ix_timeline_tracks_workspace_id'), 'timeline_tracks', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_table('project_members',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    op.create_table('timeline_items',
    sa.Column('timeline_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('shot_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('start_seconds', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['timeline_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_items_project_id'), 'timeline_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_timeline_items_workspace_id'), 'timeline_items', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_items_workspace_id'), table_name='timeline_items')
    op.drop_index(op.f('ix_timeline_items_project_id'), table_name='timeline_items')
    op.drop_table('timeline_items')
    op.drop_table('project_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_timeline_tracks_workspace_id'), table_name='timeline_tracks')
    op.drop_index(op.f('ix_timeline_tracks_project_id'), table_name='timeline_tracks')
    op.drop_table('timeline_tracks')
    op.drop_index(op.f('ix_shots_workspace_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_scene_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_project_id'), table_name='shots')
    op.drop_index(op.f('ix_shots_episode_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_usage_records_workspace_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_project_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_tool_calls_workspace_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_project_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_timelines_workspace_id'), table_name='timelines')
    op.drop_index(op.f('ix_timelines_project_id'), table_name='timelines')
    op.drop_table('timelines')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_scenes_workspace_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_project_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_episode_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_pending_actions_workspace_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_project_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_knowledge_versions_workspace_id'), table_name='knowledge_versions')
    op.drop_index(op.f('ix_knowledge_versions_project_id'), table_name='knowledge_versions')
    op.drop_table('knowledge_versions')
    op.drop_index(op.f('ix_generation_outputs_workspace_id'), table_name='generation_outputs')
    op.drop_index(op.f('ix_generation_outputs_project_id'), table_name='generation_outputs')
    op.drop_table('generation_outputs')
    op.drop_index(op.f('ix_character_versions_workspace_id'), table_name='character_versions')
    op.drop_index(op.f('ix_character_versions_project_id'), table_name='character_versions')
    op.drop_index(op.f('ix_character_versions_character_id'), table_name='character_versions')
    op.drop_table('character_versions')
    op.drop_table('users')
    op.drop_index(op.f('ix_story_sources_workspace_id'), table_name='story_sources')
    op.drop_index(op.f('ix_story_sources_project_id'), table_name='story_sources')
    op.drop_table('story_sources')
    op.drop_index(op.f('ix_project_bibles_workspace_id'), table_name='project_bibles')
    op.drop_index(op.f('ix_project_bibles_project_id'), table_name='project_bibles')
    op.drop_table('project_bibles')
    op.drop_index(op.f('ix_outbox_events_workspace_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_project_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_knowledge_documents_workspace_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_project_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('ix_generation_status_lease', table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_workspace_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_project_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_episodes_workspace_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_project_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_characters_workspace_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_project_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_character_relationships_workspace_id'), table_name='character_relationships')
    op.drop_index(op.f('ix_character_relationships_project_id'), table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_workspace_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_agent_runs_workspace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
